#version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: matching
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: matching_user
      MYSQL_PASSWORD: matching_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - matching-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - matching-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matching
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8081:8080"
    networks:
      - matching-network

volumes:
  mysql-data:

networks:
  matching-network:
    driver: bridge
